# Numpy Class Notes

Short for Numerical Python.
Library used for numerical computing.

### Import

In [1]:
import numpy as np

### Numpy Arrays

Basic data structures in Numpy: array (list within list)
All elements should share type (normally numbers)

In [3]:
a = np.random.random((10,4))
print(a)
# shape(rowsxnumbers)
print(a.shape)
# size (number of elements in my array)
print(a.size)

[[0.57031067 0.06495738 0.31092385 0.71475365]
 [0.62682039 0.93421296 0.93669282 0.50996161]
 [0.85478742 0.9655422  0.04868485 0.80485552]
 [0.09692449 0.06010178 0.9521404  0.42814269]
 [0.60509828 0.79101139 0.20605107 0.71415216]
 [0.1397359  0.9960845  0.48520073 0.23451147]
 [0.69921264 0.14458602 0.983885   0.14166349]
 [0.79070548 0.21344035 0.31826426 0.54329763]
 [0.35155537 0.4722951  0.4820516  0.84897032]
 [0.75866268 0.14008545 0.97192889 0.33293434]]
(10, 4)
40


### Extracting data

In [8]:
# Create an array with two groups of three 4x5 matrices
c = np.random.random((2,3,4,5))
print(c)

[[[[0.60403388 0.69986042 0.89247018 0.03496133 0.97578418]
   [0.24308324 0.34230272 0.77195984 0.50451458 0.91417689]
   [0.38323058 0.5981716  0.57024234 0.36985688 0.2116114 ]
   [0.94880649 0.58865565 0.85824355 0.5346257  0.82523686]]

  [[0.98738265 0.35396934 0.57818828 0.31363266 0.16908366]
   [0.80708007 0.16115267 0.4980529  0.71168506 0.71991857]
   [0.58662338 0.87872947 0.61821654 0.63835062 0.2469996 ]
   [0.61647645 0.05418099 0.79008587 0.59788295 0.77833053]]

  [[0.60699694 0.71289357 0.21895577 0.58580031 0.32115232]
   [0.19301809 0.29086983 0.56787012 0.50560823 0.12838213]
   [0.34994077 0.44251861 0.46143312 0.79072773 0.89712132]
   [0.94410756 0.9189956  0.84233655 0.2465726  0.10060109]]]


 [[[0.38560129 0.64640079 0.34165903 0.56756393 0.37149814]
   [0.95827371 0.80104434 0.60172249 0.95266747 0.49943182]
   [0.89251519 0.30887276 0.68872999 0.51599623 0.65379065]
   [0.13463874 0.98660544 0.41132934 0.87948722 0.68541494]]

  [[0.73374164 0.76620601 0.59

First group of array c:

In [9]:
print(c[0])

[[[0.60403388 0.69986042 0.89247018 0.03496133 0.97578418]
  [0.24308324 0.34230272 0.77195984 0.50451458 0.91417689]
  [0.38323058 0.5981716  0.57024234 0.36985688 0.2116114 ]
  [0.94880649 0.58865565 0.85824355 0.5346257  0.82523686]]

 [[0.98738265 0.35396934 0.57818828 0.31363266 0.16908366]
  [0.80708007 0.16115267 0.4980529  0.71168506 0.71991857]
  [0.58662338 0.87872947 0.61821654 0.63835062 0.2469996 ]
  [0.61647645 0.05418099 0.79008587 0.59788295 0.77833053]]

 [[0.60699694 0.71289357 0.21895577 0.58580031 0.32115232]
  [0.19301809 0.29086983 0.56787012 0.50560823 0.12838213]
  [0.34994077 0.44251861 0.46143312 0.79072773 0.89712132]
  [0.94410756 0.9189956  0.84233655 0.2465726  0.10060109]]]


Second subgroup of the first group:

In [10]:
print(c[0,1])

[[0.98738265 0.35396934 0.57818828 0.31363266 0.16908366]
 [0.80708007 0.16115267 0.4980529  0.71168506 0.71991857]
 [0.58662338 0.87872947 0.61821654 0.63835062 0.2469996 ]
 [0.61647645 0.05418099 0.79008587 0.59788295 0.77833053]]


Fourth column of the second subgroup:

In [11]:
print(c[0,1,:,3])

[0.31363266 0.71168506 0.63835062 0.59788295]


### Convert data structures to arrays

In [12]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Math Functions

Sum of all elements in matrix a:

In [13]:
print(np.sum(a))

21.245196852526007


Sum of each row in matrix a:
(axis = 0 for columns)

In [14]:
print(np.sum(a, axis=1))

[1.66094556 3.00768778 2.67387    1.53730937 2.31631291 1.85553261
 1.96934715 1.86570772 2.1548724  2.20361136]


Subtract elements of x from elements of y:

In [15]:
print(np.subtract(y,x))

NameError: name 'y' is not defined

## Code along

In [ ]:
import numpy as np

In [22]:
numbers = [1,2,3,4,5]

In [31]:
def sumint(x):
    tot = 0
    for i in x:
        if type(i) == int:
            tot += i
        else:
            return "Error: at least one element of the list is not an integer"
    return tot

In [32]:
sumint(numbers)

15

Convert into an array:

In [34]:
a = np.array(numbers)

In [35]:
a[0]

1

Shape:

In [37]:
np.shape(a)
# Me va devolver 5 de una sola dimensión

(5,)

Suma:

In [38]:
np.sum(a)

15

Create a two dimension array:

In [40]:
b = np.array([[1,2,3], [4,5,6]])

Print shape and experiments:

In [41]:
print(np.shape(b))
print(b.shape)

(2, 3)
(2, 3)


In [42]:
print(b[0,0], b[1,0], b[1,2])

1 4 6


Crear función para convertir lista en array y sumarla:

In [68]:
def sumarr(lst):
    l_t_a = np.array(lst)
    return np.sum(l_t_a)

In [47]:
def sumarr(lst):
    return np.array(lst).sum()

Escribir la función para que nos haga la operación que le metamos en el segundo parámetro

In [60]:
def calculator(lst, operation):
    result = operation(np.array(lst))
    return result

In [65]:
calculator([3,2,3], np.mean)

2.6666666666666665

Define a matrix as a list then convert to array:

In [67]:
mat = [[1,2,3], [4,5,6], [8,9,7]]

In [72]:
mat = np.array(mat)

Definde a random matrix:

In [74]:
random_mat = np.random.random((3,3))
print(random_mat)

[[0.21665698 0.82140839 0.09101733]
 [0.32865586 0.68954443 0.50711621]
 [0.60789242 0.30984503 0.7409645 ]]


Sum all matrix and then only rows and only columns:

In [75]:
random_mat.sum()

4.31310113616513

In [76]:
random_mat.sum(axis=0)

array([1.15320525, 1.82079785, 1.33909804])

In [77]:
random_mat.sum(axis=1)

array([1.1290827 , 1.5253165 , 1.65870194])

In [78]:
#Esto lo podemos hacer para todas las funciones

Create empty matrix:

In [81]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [82]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [83]:
a = np.ones((2,3), dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


Create an array with a fixed basal number other than one or zero:

In [85]:
c = np.full((2,3),7)
print(c)

[[7 7 7]
 [7 7 7]]


Create identity(mirror) matrix:

In [87]:
d = np.eye(2, dtype=int)
print(d)

[[1 0]
 [0 1]]


Create and array 3x4 two dim array:

In [90]:
c = np.random.random((3,4))
print(c)

[[0.24813483 0.22549941 0.09902239 0.05449997]
 [0.54730716 0.001805   0.34492737 0.90144305]
 [0.21094108 0.53361726 0.07930484 0.36503926]]


new array with cols 1 and 2 from row 1 and 2:

In [94]:
b = c[:2,:2]
print(b)

[[0.24813483 0.22549941]
 [0.54730716 0.001805  ]]


Two 3x3 matrices then sum them

In [107]:
mat1 = np.random.random((3,3))
mat2 = np.random.random((3,3))
mat1
mat2

array([[0.39188213, 0.58007983, 0.72423317],
       [0.65330332, 0.5559283 , 0.05179208],
       [0.94382402, 0.35989848, 0.1365209 ]])

In [111]:
np.add(mat1,mat2) 
# Se usa ADD para usar dos matrices elementwise

array([[1.36839946, 0.88869789, 0.87637121],
       [0.8998228 , 1.36761378, 0.62291751],
       [1.00005666, 0.69758261, 0.50886893]])

In [112]:
np.subtract(mat1,mat2)

array([[ 0.58463519, -0.27146178, -0.57209514],
       [-0.40678384,  0.25575719,  0.51933334],
       [-0.88759137, -0.02221435,  0.23582713]])

In [113]:
np.divide(mat1,mat2)

array([[ 2.49186487,  0.53202687,  0.21006776],
       [ 0.37734307,  1.46005427, 11.02727316],
       [ 0.05957959,  0.93827607,  2.72740671]])

In [114]:
np.multiply(mat1,mat2)

array([[0.38267969, 0.17902311, 0.11018341],
       [0.161052  , 0.45123893, 0.02957977],
       [0.05307372, 0.121532  , 0.05083329]])